os: linux
language: cpp
dist: bionic
sudo: false

addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-8-dev
      - libc++-8-dev
      - g++-8

# Setup compilers.
compiler:
  - clang
  - gcc

# Build matrix
#matrix:
#  fast_finish: true
#  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL=

# Setup cmake.
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCCLI_BUILD_SHARED=ON -DCCLI_BUILD_EXAMPLES=ON -DCCLI_BUILD_TESTS=ON -DCCLI_BUILD_WARNINGS=ON

# Build.
script:
  - cmake --build ./ -- -j2
  - ctest -j2 -V --output-on-failure