os: linux
language: cpp
dist: bionic
sudo: false

# Setup compilers.
compiler:
  - clang
  - gcc

# Setup cmake.
before_script:
  - mkdir build
  - cd build
  - cmake ..

# Build.
script:
  - cmake --build ./ -- -j2