os: linux
language: cpp
dist: bionic
sudo: false

# Setup compilers.
compiler:
  - clang
  - gcc

# Setup cmake.
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCCLI_BUILD_SHARED=ON -DCCLI_BUILD_EXAMPLES=ON -DCCLI_BUILD_TESTS=ON -DCCLI_BUILD_WARNINGS=ON

# Build.
script:
  - cmake --build ./ -- -j2
  - ctest -j2 --output-on-failure