os: linux
language: cpp
dist: bionic
sudo: false

addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-7-dev
      - libc++-dev

# Setup compilers.
compiler:
  - clang
  - gcc

# Setup cmake.
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCCLI_BUILD_SHARED=ON -DCCLI_BUILD_EXAMPLES=ON -DCCLI_BUILD_TESTS=ON -DCCLI_BUILD_WARNINGS=ON

# Build.
script:
  - cmake --build ./ -- -j2
  - ctest -j2 -V --output-on-failure