# Adapted from:
# https://github.com/gabime/spdlog
image:
  - Visual Studio 2017

clone_folder: c:\projects\source

branches:
  only:
    - master
    - development

environment:
  matrix:
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Debug
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'ON'
#    - GENERATOR: '"Visual Studio 14 2015"'
#      BUILD_TYPE: Debug
#      BUILD_SHARED: 'OFF'
#    - GENERATOR: '"Visual Studio 14 2015"'
#      BUILD_TYPE: Release
#      BUILD_SHARED: 'OFF'
#    - GENERATOR: '"Visual Studio 14 2015 Win64"'
#      BUILD_TYPE: Debug
#      BUILD_SHARED: 'OFF'
#    - GENERATOR: '"Visual Studio 14 2015 Win64"'
#      BUILD_TYPE: Release
#      BUILD_SHARED: 'OFF'

build_script:
  - cmd: >-
      mkdir build

      cd build

      cmake c:\projects\source -G %GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCCLI_BUILD_SHARED=%BUILD_SHARED% -DCCLI_BUILD_EXAMPLES=ON -DCCLI_BUILD_TESTS=ON -DCCLI_BUILD_WARNINGS=ON

      cmake --build . --config %BUILD_TYPE%

before_test:
  - set PATH=%PATH%;C:\projects\source\build\%BUILD_TYPE%

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#test_script:
#  - C:\projects\source\build\tests\%BUILD_TYPE%\ccli_tests.exe