image:
  - Visual Studio 2017

clone_folder: c:\projects\source

environment:
  matrix:
    - GENERATOR: '"Visual Studio 14 2015"'
      BUILD_TYPE: Debug
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 14 2015"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 14 2015 Win64"'
      BUILD_TYPE: Debug
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 14 2015 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Debug
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'ON'

build_script:
  - cmd: >-
      mkdir build

      cd build

      cmake c:\projects\source -G %GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCCLI_BUILD_SHARED=%BUILD_SHARED% -DCCLI_BUILD_EXAMPLES=ON -DCCLI_BUILD_TESTS=ON

      cmake --build . --config %BUILD_TYPE%